title: Jay Thanki
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Jay Thanki # add your name
author-img: Jay B&W.jpg # add your photo
about-author: I am a Software Developer and I like to build full stack applications which can be of use to everyone. I also love learning new concepts in programming in general and will be documenting all the knowledge gained from my endeavour through this blog. Always hungry to keep learning. # add description
social-twitter: thankijay99
# social-facebook: # add your Facebook handle
social-github: jaythanki23 
social-linkedin: jaythanki99/
social-email: thankijay99@gmail.com

# Disqus
# discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
